gradient_accumulation_steps: 5
max_grad_norm: 1
num_train_epochs: 200
val_datasets: "text2obj_val"
cpu_offload: False
working_dir: '/data/home/2024120101018/linzhuohang/3DGen/3DGen_new'
data_dir: '/data/home/2024120101018/linzhuohang/3DGen/data'
model_dir: '/data/home/2024120101018/linzhuohang/3DGen/data/hf/hub/models--black-forest-labs--FLUX.1-Kontext-dev/snapshots/af58063aa431f4d2bbc11ae46f57451d4416a170'
log_interval: 5
learning_rate: 1e-5
gradient_checkpointing: False
no_data_stack: False
image_resolution: 512
vae_train_strategy: 'frozen' # 'frozen' 'encoder_last' 'all' 'decoder_last'
use_pred_angle: False
dino_path: '/data/home/2024120101018/linzhuohang/3DGen/data/dinov3'
feature_loss_weight: 0.5
cls_loss_weight: 1
flow_loss_weight: 100
trellis_train:
  regressor_weights_path: "/data/home/2024120101018/linzhuohang/3DGen/data/angle_predictor.bin"
  adapter_init_weights_path: "/data/home/2024120101018/linzhuohang/3DGen/data/elevation_adapter3_7.bin"
  pipeline_path: "microsoft/TRELLIS.2-4B"
  record_tgt_paths_onqy: false
dataset:
#  video_size: [16, 3, 384, 704] # [16, 3, 320, 768] [16, 3, 384, 704]
#  video_fps: 8
#  p_uncond: 0.2

  text2obj:
    # data_dir: '/mnt/hdd1/caixiao/data/pv_views_64_1'
    # data_dir: '/mnt/hdd1/data/select_data1.json'
    #data_dir: '/mnt/hdd1/caixiao/data/objaverse_1.0/utils/data_select/objaverse_qilian_WB.json'
    # data_dir: '/home/caixiao/projects/3DGen/data/3DTopia-objaverse-caption-361k.json'
    # data_dir: '/home/caixiao/projects/3d_lib/img/filter_data_v2.json'
    # data_dir: '/mnt/hdd1/caixiao/3dgen/nerf/white_test2/part5.json'
    #data_dir : '/mnt/hdd1/data/select_data1.json'

    #data_dir: '/mnt/hdd1/caixiao/data/objaverse_1.0/utils/data_select/rgb2.json'
    data_dir: 'configs/regularview_300k.json'
    #data_dir: 'configs/elevation_train.json'
    #root: "/data/home/2024120101018/linzhuohang/3DGen/data/high_score_25k"
    #data_dir: 'configs/select_data2.json'
    #data_dir: 'configs/multiview_300k.json'
    # view_num: 16
  #multi_view:
    #data_dir: 'configs/elevation.json'
    #root: "/data/home/2024120101018/linzhuohang/3DGen/data/high_score_25k "
  text2obj_val:
    data_dir: 'configs/regularview_300k_val.json'
    #data_dir: 'configs/elevation_val.json'
    #root: "/data/home/2024120101018/linzhuohang/3DGen/data/high_score_25k"

    #data_dir: '/mnt/hdd1/caixiao/data/objaverse_1.0/utils/data_select/rgb2.json'
    #data_dir: 'configs/multiview_300k_2.json'
    #data_dir: 'configs/elevation.json'
    #root: "/data/home/2024120101018/linzhuohang/3DGen/data/high_score_25k "
    #data_dir : '/mnt/hdd1/data/select_data1.json'
    #data_dir: 'configs/gso.json'
    #data_dir: 'configs/gso_model.json'
    #data_dir: 'configs/random_view.json'
  elevation:
    use_pipeline_predictor: true
    pipeline_weights_path: /data/home/2024120101018/linzhuohang/3DGen/data/angle_predictor.bin
    pipeline_dino_image_size: 512
    reload_interval_steps: 10
    inference_output_path: /data/home/2024120101018/linzhuohang/3DGen/data/testset/group_view/angle_pred.json
    inference_image_dir: /data/home/2024120101018/linzhuohang/3DGen/data/testset/group_view/HighElevation_0Roll
  elavation_train:
    # data_dir: 'configs/elevation_train.json'
    # root: "/data/home/2024120101018/linzhuohang/3DGen/data/high_score_25k"
    data_dir: 'configs/regularview_300k.json'
    # root: "/data/home/2024120101018/linzhuohang/3DGen/data/regularview_300k"
    # data_dir: 'configs/random_view.json'
    #root: "/data/home/2024120101018/linzhuohang/3DGen/data/random_view"
    # processor: pair_dataset
    processor: ElevationIterableDataset
  elavation_val:
    # data_dir: 'configs/elevation_val.json'
    # root: "/data/home/2024120101018/linzhuohang/3DGen/data/high_score_25k"
    data_dir: 'configs/regularview_300k_val.json'
    # root: "/data/home/2024120101018/linzhuohang/3DGen/data/regularview_300k"
    # data_dir: 'configs/random_view_val.json'
    #root: "/data/home/2024120101018/linzhuohang/3DGen/data/random_view"
    # processor: pair_dataset
    processor: ElevationIterableDataset
  rotator_train:
    #data_dir: 'configs/regularview_300k.json'
    #root: "/data/home/2024120101018/linzhuohang/regularview_300k"
    data_dir: configs/random_view.json
    root: /data/home/2024120101018/linzhuohang/random_view
    glb_db: glb_index.sqlite
    glb_root: /mnt/hdd1/caixiao/data/objaverse_1.0/hf-objaverse-v1/glbs/
  rotator_val:
    #data_dir: 'configs/regularview_300k_val.json'
    #root: "/data/home/2024120101018/linzhuohang/3DGen/data/regularview_300k"
    data_dir: configs/random_view_val.json
    root: /data/home/2024120101018/linzhuohang/random_view
    glb_db: glb_index.sqlite
    glb_root: /mnt/hdd1/caixiao/data/objaverse_1.0/hf-objaverse-v1/glbs/
  render_sparse:
    data_dir: data_queue/tgt_paths_rank3.json
  text2render:
    # data_dir: '/mnt/hdd1/caixiao/data/pv_views_64_1'
    data_dir: '/mnt/hdd1/data/select_data1.json'
    # data_dir: '/home/caixiao/projects/3DGen/data/filtered_sd_scores.json'
    # data_dir: '/home/caixiao/projects/3d_lib/img/filter_data_v2.json'
    # data_dir: '/mnt/hdd1/caixiao/3dgen/nerf/white_test2/part5.json'
    # view_num: 16
  
  text2scene:
    data_dir: '/mnt/nfs/caixiao/datasets/blendedMVS/select'
    view_num: 16

ddconfig:
  ema: False
  lpips: true
  diff_latent_res_H: 64 # 88 40
  diff_latent_res_W: 64 # 48 96

  base_learning_rate: 5.0e-5
  # ema: true
  # lpips: true
  # base_learning_rate: 5.0e-4
  precrop_frac: 0.5
  precrop_iters: 1000
  N_rand: 1024
  # diff_latent_res_H: 64 # 88 40
  # diff_latent_res_W: 64 # 48 96
  plane_C: 4
  
  # base_learning_rate: 1.0e-4
  neural_rendering_resolution: 64
  clamp_mode: 'softplus'
  disparity_space_sampling: False
  depth_resolution: 64
  depth_resolution_importance: 64  #64
  ray_start: 'auto'
  ray_end: 'auto'
  # ray_start: 0.1
  # ray_end: 2.6
  box_warp: 1.9
  white_back: False
  avg_camera_radius: 1.7
  avg_camera_pivot: [0, 0, 0]
