name: "zero123-ft"
tag: "val-35-ft-group-angle_pred"
exp_root_dir: "outputs"
use_timestamp: true

data_type: "zero123-pair-datamodule"
data:
  train_manifest: /data/home/2024120101018/linzhuohang/3DGen/data/zero123_random_view_ft/train.jsonl
  val_manifest: /data/home/2024120101018/linzhuohang/3DGen/data/zero123_random_view_ft/val_35_select_pred.jsonl
  image_size: 256
  batch_size: 12
  num_workers: 4
  shuffle: true
  default_target_elev: 15.0

system_type: "zero123-finetune-system"
resume: /data/home/2024120101018/linzhuohang/3DGen/3DGen_new/modules/threestudio/outputs/zero123-ft/35-ft/ckpts/epoch=4-step=100000.ckpt
system:
  pretrained_model_name_or_path: "./load/zero123/stable_zero123.ckpt"
  #pretrained_model_name_or_path: /data/home/2024120101018/linzhuohang/3DGen/3DGen_new/modules/threestudio/outputs/zero123-ft/base/save/checkpoints/full_model_init_step_10000.ckpt
  pretrained_config: "./load/zero123/sd-objaverse-finetune-c_concat-256.yaml"
  val_filename_with_batch_item_suffix: false
  train_unet: true
  train_cc_projection: true
  train_cond_stage: false
  train_first_stage: false

  lr: 2.0e-6
  lr_t_max: 10000
  lr_eta_min: 1e-7
  val_guidance_scale: 1
  betas: [0.9, 0.999]
  weight_decay: 1.0e-2

trainer:
  max_steps: 100000
  log_every_n_steps: 5
  num_sanity_val_steps: 1
  val_check_interval: 1
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: 1000